version: '3.9'
name: tp0
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    networks:
      - testing_net

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    build:
      dockerfile: server/server.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq
    volumes:
      - ./server/config.ini:/config.ini

  client:
    image: client:latest
    entrypoint: python3 /main.py
    deploy:
      replicas: ${CLIENT_REPLICAS}
    build:
      dockerfile: client/client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini
      - ./client/data/:/data/

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
